#!/usr/bin/env python3
"""Convert the individual single revocable trust form into a template."""

from pathlib import Path

from docx import Document


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "source-forms" / "trust" / "Individual-Single Revocable Trust.docx"
TARGET = ROOT / "templates" / "trust-individual-single.docx"


REPLACEMENTS = {
    "[TRUST NAME]": "{{ trust.name | name }}",
    "[CLIENT]": "{{ client.full_name | name }}",
    "[DocDate]": "{{ trust.display_date }}",
    "[COUNTY]": "{{ execution.display_signing_county | name }}",
    "[ID_TYPE]": "{{ execution.id_type }}",
    "[NotaryExpiration]": "{{ execution.display_notary_commission }}",
    "[he/she]": "{{ client.pronoun_subject }}",
    "[his/her/their]": "{{ client.pronoun_possessive }}",
    "[CONTINGENT_BENEFICIARY]": "{{ trust.contingent_beneficiary.full_name | name }}",
    "[DISTRIBUTION_AGE]": "{{ trust.descendants_distribution.distribution_age }}",
    "[STAGE_1_AGE]": "{{ trust.descendants_distribution.stage_1_age }}",
    "[STAGE_2_AGE]": "{{ trust.descendants_distribution.stage_2_age }}",
    "[STAGE_3_AGE]": "{{ trust.descendants_distribution.stage_3_age }}",
    "[REMOTE_BENEFICIARY_CHARITY]": "{{ trust.remote_beneficiaries.charity.name | name }}",
    "[FIRST_SUCCESSOR_TRUSTEE]": "{{ fiduciaries.trustee.primary.full_name | name }}",
    "[SECOND_SUCCESSOR_TRUSTEE]": "{{ fiduciaries.trustee.successor.full_name | name }}",
    "[THIRD_SUCCESSOR_TRUSTEE]": "{{ fiduciaries.trustee.second_successor.full_name | name }}",
}


PARAGRAPH_REPLACEMENTS = {
    "[TRUST NAME]": "{{ trust.name | name }}",
    "The Grantor is unmarried.  The Grantor's children born before the date of this Trust Agreement are [CHILD] and [CHILD].  All references in this Trust Agreement to the Grantor's children are to these children, as well as to any children later born to or adopted by the Grantor in a legal proceeding valid in the domestic or foreign jurisdiction in which it occurred.  References to the Grantor's descendants are to the Grantor's children and their descendants, including descendants of any deceased child.":
        "The Grantor is unmarried.{% if has_children %} The Grantor's children born before the date of this Trust Agreement are {% for child in children %}{{ child.full_name | name }}{% if not loop.last %}, {% endif %}{% endfor %}. All references in this Trust Agreement to the Grantor's children are to these children, as well as to any children later born to or adopted by the Grantor in a legal proceeding valid in the domestic or foreign jurisdiction in which it occurred. References to the Grantor's descendants are to the Grantor's children and their descendants, including descendants of any deceased child.{% endif %}",
    "The Grantor specifically disinherits [DISINHERIT] and [DISINHERIT]'s descendants.  For all purposes of this Trust Agreement, [DISINHERIT] and [DISINHERIT]'s descendants shall be considered to have predeceased the Grantor.  Although [DISINHERIT] is a natural heir of the Grantor, the Grantor has intentionally not provided for [DISINHERIT] as a beneficiary under this Trust Agreement.":
        "{% if trust.disinherited %}The Grantor specifically disinherits {% for person in trust.disinherited %}{{ person.full_name | name }}{% if not loop.last %}, {% endif %}{% endfor %} and their descendants. For all purposes of this Trust Agreement, each such person and that person's descendants shall be considered to have predeceased the Grantor. Although each such person may be a natural heir of the Grantor, the Grantor has intentionally not provided for such person as a beneficiary under this Trust Agreement.{% endif %}",
    "General Gift of Tangible Personal Property.  The Grantor gives all the Grantor's tangible personal property held in the Trust Fund (other than items effectively disposed of above) as provided in this paragraph.  The Grantor gives such property to such of the Grantor's children as survive the Grantor, to be divided among them as they may agree in as nearly equal shares as practicable or, in the absence of agreement, as the Trustee shall determine.  The Trustee shall sell or donate, as the Trustee shall determine in the Trustee's sole and absolute discretion, any such property which the Grantor's children determine they do not want to keep for themselves, with the proceeds of any such sales to be added to the Trust Fund.  If the Grantor dies without issue or no child of the Grantor survives the Grantor, the Grantor gives all such tangible personal property as provided in [CHOOSE ONE: subparagraph (a) (equal shares) OR subparagraph (b) (priority order)] below:":
        "General Gift of Tangible Personal Property. The Grantor gives all the Grantor's tangible personal property held in the Trust Fund (other than items effectively disposed of above) as provided in this paragraph. The Grantor gives such property to such of the Grantor's children as survive the Grantor, to be divided among them as they may agree in as nearly equal shares as practicable or, in the absence of agreement, as the Trustee shall determine. The Trustee shall sell or donate, as the Trustee shall determine in the Trustee's sole and absolute discretion, any such property which the Grantor's children determine they do not want to keep for themselves, with the proceeds of any such sales to be added to the Trust Fund. If the Grantor dies without issue or no child of the Grantor survives the Grantor, the Grantor gives all such tangible personal property as provided in {% if trust.tangible_personal_property.distribution_method == 'equal_shares' %}subparagraph (a){% elif trust.tangible_personal_property.distribution_method == 'priority_order' %}subparagraph (b){% else %}the applicable subparagraph{% endif %} below:",
    "(a) Equal Shares Among Named Individuals.  The Grantor gives all such tangible personal property to [TPP_BENEFICIARIES] who survive the Grantor, to be divided among them as they may agree in as nearly equal shares as practicable or, in the absence of agreement, as the Trustee shall determine.  The Trustee shall sell or donate, as the Trustee shall determine in the Trustee's sole and absolute discretion, any such property which such individuals determine they do not want to keep for themselves, with the proceeds of any such sales to be added to the Residuary Trust Fund.  If none of the individuals named in [TPP_BENEFICIARIES] survives the Grantor, the Trustee shall add all such tangible personal property (or the proceeds of sale thereof) to the Residuary Trust Fund.":
        "{% if trust.tangible_personal_property.distribution_method == 'equal_shares' %}(a) Equal Shares Among Named Individuals. The Grantor gives all such tangible personal property to {% for person in trust.tangible_personal_property.beneficiaries %}{{ person.full_name | name }}{% if not loop.last %}, {% endif %}{% endfor %} who survive the Grantor, to be divided among them as they may agree in as nearly equal shares as practicable or, in the absence of agreement, as the Trustee shall determine. The Trustee shall sell or donate, as the Trustee shall determine in the Trustee's sole and absolute discretion, any such property which such individuals determine they do not want to keep for themselves, with the proceeds of any such sales to be added to the Residuary Trust Fund. If none of the individuals named above survives the Grantor, the Trustee shall add all such tangible personal property (or the proceeds of sale thereof) to the Residuary Trust Fund.{% endif %}",
    "(b) Priority Order — First Survivor Takes.  The Grantor gives all such tangible personal property to the first of the following persons who survives the Grantor, outright: (i) [TPP_BENEFICIARY_1]; (ii) [TPP_BENEFICIARY_2]; (iii) [TPP_BENEFICIARY_3].  The Trustee shall sell or donate, as the Trustee shall determine in the Trustee's sole and absolute discretion, any such property which such individual determines he or she does not want to keep, with the proceeds of any such sales to be added to the Residuary Trust Fund.  If none of the foregoing individuals survives the Grantor, the Trustee shall add all such tangible personal property (or the proceeds of sale thereof) to the Residuary Trust Fund.":
        "{% if trust.tangible_personal_property.distribution_method == 'priority_order' %}(b) Priority Order - First Survivor Takes. The Grantor gives all such tangible personal property to the first of the following persons who survives the Grantor, outright: {% for person in trust.tangible_personal_property.priority_beneficiaries %}{{ loop.index }}. {{ person.full_name | name }}{% if not loop.last %}; {% endif %}{% endfor %}. The Trustee shall sell or donate, as the Trustee shall determine in the Trustee's sole and absolute discretion, any such property which such individual determines he or she does not want to keep, with the proceeds of any such sales to be added to the Residuary Trust Fund. If none of the foregoing individuals survives the Grantor, the Trustee shall add all such tangible personal property (or the proceeds of sale thereof) to the Residuary Trust Fund.{% endif %}",
    "[CHOOSE ONE: subparagraph (A) (outright distribution at Grantor's death) OR subparagraph (B) (staged-age withdrawal rights)] shall govern the Beneficiary's right to receive principal:":
        "{% if trust.descendants_distribution.method == 'outright' %}Subparagraph (A) shall govern the Beneficiary's right to receive principal:{% elif trust.descendants_distribution.method == 'staged' %}Subparagraph (B) shall govern the Beneficiary's right to receive principal:{% endif %}",
    "(A) Outright Distribution at Grantor's Death.  Notwithstanding anything in this Article to the contrary, upon the Grantor's death the Trustee shall distribute each Beneficiary's share of the Trust Fund outright and free of trust to the Beneficiary, and no continuing Descendant's Separate Trust shall be established for such Beneficiary.  If the Beneficiary is then under the age of [DISTRIBUTION_AGE] years (or, if no age is specified, twenty-one (21) years), the Trustee may, in the Trustee's sole and absolute discretion, retain such Beneficiary's share in trust for the Beneficiary's benefit under the terms of this Article until the Beneficiary attains such age, at which time the trust shall terminate and the remaining trust property shall be distributed outright and free of trust to the Beneficiary.":
        "{% if trust.descendants_distribution.method == 'outright' %}(A) Outright Distribution at Grantor's Death. Notwithstanding anything in this Article to the contrary, upon the Grantor's death the Trustee shall distribute each Beneficiary's share of the Trust Fund outright and free of trust to the Beneficiary, and no continuing Descendant's Separate Trust shall be established for such Beneficiary. If the Beneficiary is then under the age of {{ trust.descendants_distribution.distribution_age }} years, the Trustee may, in the Trustee's sole and absolute discretion, retain such Beneficiary's share in trust for the Beneficiary's benefit under the terms of this Article until the Beneficiary attains such age, at which time the trust shall terminate and the remaining trust property shall be distributed outright and free of trust to the Beneficiary.{% endif %}",
    "(B) Staged-Age Withdrawal Rights.  The Beneficiary shall have the following rights to withdraw principal from the Beneficiary's trust:":
        "{% if trust.descendants_distribution.method == 'staged' %}(B) Staged-Age Withdrawal Rights. The Beneficiary shall have the following rights to withdraw principal from the Beneficiary's trust:{% endif %}",
    "(i) At any time, the Beneficiary shall have the right individually to withdraw principal for the Beneficiary's health, education, maintenance or support, in his or her accustomed manner of living;":
        "{% if trust.descendants_distribution.method == 'staged' %}(i) At any time, the Beneficiary shall have the right individually to withdraw principal for the Beneficiary's health, education, maintenance or support, in his or her accustomed manner of living;{% endif %}",
    "(ii) After the Beneficiary has attained the age of [STAGE_1_AGE] (or, if no age is specified, twenty-five (25)) years, the Beneficiary may withdraw up to one-third (1/3) of the principal of the trust as then constituted;":
        "{% if trust.descendants_distribution.method == 'staged' %}(ii) After the Beneficiary has attained the age of {{ trust.descendants_distribution.stage_1_age }} years, the Beneficiary may withdraw up to one-third (1/3) of the principal of the trust as then constituted;{% endif %}",
    "(iii) After the Beneficiary has attained the age of [STAGE_2_AGE] (or, if no age is specified, thirty (30)) years, the Beneficiary may withdraw up to one-half (1/2) of the principal of the trust as then constituted (after giving effect to any prior withdrawal under clause (ii) above); and":
        "{% if trust.descendants_distribution.method == 'staged' %}(iii) After the Beneficiary has attained the age of {{ trust.descendants_distribution.stage_2_age }} years, the Beneficiary may withdraw up to one-half (1/2) of the principal of the trust as then constituted (after giving effect to any prior withdrawal under clause (ii) above); and{% endif %}",
    "(iv) After the Beneficiary has attained the age of [STAGE_3_AGE] (or, if no age is specified, thirty-five (35)) years, the Beneficiary may withdraw the remaining principal of the trust at any time.  ":
        "{% if trust.descendants_distribution.method == 'staged' %}(iv) After the Beneficiary has attained the age of {{ trust.descendants_distribution.stage_3_age }} years, the Beneficiary may withdraw the remaining principal of the trust at any time.{% endif %}",
    "Notwithstanding anything herein contained to the contrary, the Trustee shall not distribute any portion of the Trust, or any income attributable thereto, that is subject to withdrawal by the Beneficiary to anyone other than the Beneficiary.  The Trustee shall distribute, upon the Beneficiary's death, to the estate of the Beneficiary (and not pursuant to the paragraph entitled \"Upon Beneficiary's Death\") any principal, and any income attributable thereto, that was subject to withdrawal by the Beneficiary at the time of the Beneficiary's death and not yet withdrawn by the Beneficiary.    ":
        "{% if trust.descendants_distribution.method == 'staged' %}Notwithstanding anything herein contained to the contrary, the Trustee shall not distribute any portion of the Trust, or any income attributable thereto, that is subject to withdrawal by the Beneficiary to anyone other than the Beneficiary. The Trustee shall distribute, upon the Beneficiary's death, to the estate of the Beneficiary (and not pursuant to the paragraph entitled \"Upon Beneficiary's Death\") any principal, and any income attributable thereto, that was subject to withdrawal by the Beneficiary at the time of the Beneficiary's death and not yet withdrawn by the Beneficiary.{% endif %}",
    "The Trustee shall distribute any property that is not otherwise disposed of under this Trust Agreement as provided in [CHOOSE ONE OR MORE OF: subparagraph (a) (named individuals), subparagraph (b) (charity), OR proceed directly to subparagraph (c) (heirs at law)] below.  If subparagraph (a) and/or (b) is selected, subparagraph (c) shall apply only as a final fallback if no individual named in (a) and no organization named in (b) survives or is then in existence.":
        "The Trustee shall distribute any property that is not otherwise disposed of under this Trust Agreement as provided below. If subparagraph (a) and/or (b) is selected, subparagraph (c) shall apply only as a final fallback if no individual named in (a) and no organization named in (b) survives or is then in existence.",
    "(a) Named Individuals.  The Trustee shall distribute such property to [REMOTE_BENEFICIARY_INDIVIDUALS] who survive the Grantor (or who are then living on the date on which the interest of the last beneficiary of such property expires, as applicable), in such shares (equal or otherwise) as the Grantor has specified or, if not specified, in equal shares.  If any such named individual does not survive, that individual's share shall be added pro rata to the shares of the other named individuals who do survive.":
        "{% if trust.remote_beneficiaries.individuals %}(a) Named Individuals. The Trustee shall distribute such property to {% for person in trust.remote_beneficiaries.individuals %}{{ person.full_name | name }}{% if person.share %} ({{ person.share }}){% endif %}{% if not loop.last %}, {% endif %}{% endfor %} who survive the Grantor (or who are then living on the date on which the interest of the last beneficiary of such property expires, as applicable), in such shares as the Grantor has specified or, if not specified, in equal shares. If any such named individual does not survive, that individual's share shall be added pro rata to the shares of the other named individuals who do survive.{% endif %}",
    "(b) Charity.  The Trustee shall distribute such property to [REMOTE_BENEFICIARY_CHARITY], a charitable organization described in Code Secs. 170(c), 2055(a) and 2522(a), to be used for its general charitable purposes, or in such shares among multiple such organizations as the Grantor has specified.  If a named charitable organization is not then in existence or has lost its qualification under the foregoing Code sections, the Trustee shall select one or more substitute charitable organizations qualifying under those sections that, in the Trustee's judgment, most nearly fulfill the purposes the Grantor intended.":
        "{% if trust.remote_beneficiaries.charity.name %}(b) Charity. The Trustee shall distribute such property to {{ trust.remote_beneficiaries.charity.name | name }}, a charitable organization described in Code Secs. 170(c), 2055(a) and 2522(a), to be used for its general charitable purposes, or in such shares among multiple such organizations as the Grantor has specified. If a named charitable organization is not then in existence or has lost its qualification under the foregoing Code sections, the Trustee shall select one or more substitute charitable organizations qualifying under those sections that, in the Trustee's judgment, most nearly fulfill the purposes the Grantor intended.{% endif %}",
    "(a) First Successor.  The Grantor appoints [FIRST_SUCCESSOR_TRUSTEE] [if co-trustees, add: and [FIRST_SUCCESSOR_COTRUSTEE]] to serve as the first successor Trustee(s).":
        "(a) First Successor. The Grantor appoints {{ fiduciaries.trustee.primary.full_name | name }}{% if fiduciaries.trustee.co_primary is defined and fiduciaries.trustee.co_primary.full_name %} and {{ fiduciaries.trustee.co_primary.full_name | name }}{% endif %} to serve as the first successor Trustee(s).",
    "(b) Second Successor.  If the persons named in subparagraph (a) above are unable or unwilling to serve, the Grantor appoints [SECOND_SUCCESSOR_TRUSTEE] [if co-trustees, add: and [SECOND_SUCCESSOR_COTRUSTEE]] to serve as the second successor Trustee(s).":
        "(b) Second Successor. If the persons named in subparagraph (a) above are unable or unwilling to serve, the Grantor appoints {{ fiduciaries.trustee.successor.full_name | name }}{% if fiduciaries.trustee.co_successor is defined and fiduciaries.trustee.co_successor.full_name %} and {{ fiduciaries.trustee.co_successor.full_name | name }}{% endif %} to serve as the second successor Trustee(s).",
    "(c) Third Successor.  If the persons named in subparagraphs (a) and (b) above are unable or unwilling to serve, the Grantor appoints [THIRD_SUCCESSOR_TRUSTEE] [if co-trustees, add: and [THIRD_SUCCESSOR_COTRUSTEE]] to serve as the third successor Trustee(s).":
        "(c) Third Successor. If the persons named in subparagraphs (a) and (b) above are unable or unwilling to serve, the Grantor appoints {{ fiduciaries.trustee.second_successor.full_name | name }}{% if fiduciaries.trustee.co_second_successor is defined and fiduciaries.trustee.co_second_successor.full_name %} and {{ fiduciaries.trustee.co_second_successor.full_name | name }}{% endif %} to serve as the third successor Trustee(s).",
    "(d) Manner of Acting When Co-Trustees Serve.  If two or more persons are appointed under this paragraph to serve concurrently as co-Trustees at a given level, [CHOOSE ONE: subparagraph (d)(i) (act together) OR subparagraph (d)(ii) (act independently)] shall govern the manner in which they act:":
        "(d) Manner of Acting When Co-Trustees Serve. If two or more persons are appointed under this paragraph to serve concurrently as co-Trustees at a given level, {% if fiduciaries.trustee.co_trustees_action == 'joint' %}subparagraph (d)(i){% else %}subparagraph (d)(ii){% endif %} shall govern the manner in which they act:",
    "(i) Act Together.  All co-Trustees serving at the same level shall act jointly with respect to all matters affecting the trust.  If two co-Trustees are serving, they shall act unanimously; if three or more co-Trustees are serving, they shall act by majority.  No co-Trustee shall have the authority to act alone with respect to trust matters except as expressly provided in this Trust Agreement or as the other co-Trustees may delegate in writing pursuant to the provisions of this Trust Agreement governing delegation among Trustees.":
        "{% if fiduciaries.trustee.co_trustees_action == 'joint' %}(i) Act Together. All co-Trustees serving at the same level shall act jointly with respect to all matters affecting the trust. If two co-Trustees are serving, they shall act unanimously; if three or more co-Trustees are serving, they shall act by majority. No co-Trustee shall have the authority to act alone with respect to trust matters except as expressly provided in this Trust Agreement or as the other co-Trustees may delegate in writing pursuant to the provisions of this Trust Agreement governing delegation among Trustees.{% endif %}",
    "(ii) Act Independently.  Each co-Trustee serving at the same level shall have the authority to act alone with respect to all matters affecting the trust, without the consent or joinder of the other co-Trustee(s); provided that any co-Trustee taking action hereunder shall use reasonable efforts to give prompt written notice of such action to the other co-Trustee(s) then serving.  Failure to provide such notice shall not invalidate the action taken.  Notwithstanding the foregoing, no co-Trustee shall take any action that another co-Trustee then serving has objected to in writing, unless and until such objection is withdrawn or resolved by agreement of all co-Trustees then serving.":
        "{% if fiduciaries.trustee.co_trustees_action != 'joint' %}(ii) Act Independently. Each co-Trustee serving at the same level shall have the authority to act alone with respect to all matters affecting the trust, without the consent or joinder of the other co-Trustee(s); provided that any co-Trustee taking action hereunder shall use reasonable efforts to give prompt written notice of such action to the other co-Trustee(s) then serving. Failure to provide such notice shall not invalidate the action taken. Notwithstanding the foregoing, no co-Trustee shall take any action that another co-Trustee then serving has objected to in writing, unless and until such objection is withdrawn or resolved by agreement of all co-Trustees then serving.{% endif %}",
}


def replace_text_preserve_first_run(paragraph, text: str) -> None:
    if not paragraph.runs:
        paragraph.add_run(text)
        return
    paragraph.runs[0].text = text
    for run in paragraph.runs[1:]:
        run.text = ""


def convert_paragraph(paragraph) -> None:
    original = paragraph.text
    normalized = original.strip()
    if normalized in PARAGRAPH_REPLACEMENTS:
        replace_text_preserve_first_run(paragraph, PARAGRAPH_REPLACEMENTS[normalized])
        return
    converted = original
    for before, after in REPLACEMENTS.items():
        converted = converted.replace(before, after)
    if converted != original:
        replace_text_preserve_first_run(paragraph, converted)


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing source form: {SOURCE}")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    doc = Document(SOURCE)
    for paragraph in doc.paragraphs:
        convert_paragraph(paragraph)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    convert_paragraph(paragraph)
    doc.save(TARGET)


if __name__ == "__main__":
    main()
